### PR TITLE
Significantly boost compile times with alternate API

### PR DESCRIPTION
**Pull request by CorvusPrudens**
## The problem

`phosphor-leptos` is a lovely icon library. However, it has surprisingly slow compile times (even for Rust)!

This is due primarily to the fact that a full Leptos component is generated for each icon. With seven `view` macros and one `component` macro, rustc ends up having to churn through a fair amount of code for every single file.

Aside from the long compile times, this component-per-icon approach likely produces larger WASM binaries than necessary. Since each icon is a unique component (and therefore a unique function), it's unlikely the Rust compiler and downstream WASM tools will be able to combine or reduce the component code in any meaningful way.

## An alternative approach

This PR introduces an alternative approach, similar to [leptos-icons](https://github.com/carloskiki/leptos-icons). That is, the library provides a single `Icon` component that takes an `icon` prop, where the prop holds the actual icon data.

This significantly reduces compile times. In my unscientific testing, a full debug build from scratch went from 92 seconds to just 17. When building a full Leptos project, `phosphor-leptos` took a nearly negligible amount of time compared to other dependencies (even with all features enabled). This should handily solve #12.

As discussed above, this new API should also minimize the size cost of using many different icons since the icon data is separate from the component code. I have not rigorously profiled this, however.

## Drawbacks

This approach is a **breaking change**. It also now requires bringing the component _and_ icon data into scope:

```rs
use phosphor_leptos::{Icon, Acorn};

view! {
    <Icon icon=Acorn />
}
```

However, in my opinion, the benefits significantly outweigh the drawbacks.

### Implementation details

Like [leptos-icons](https://github.com/carloskiki/leptos-icons), I went with PascalCase for icon data items. It's more idiomatic to use SCREAMING_SNAKE for such const items, but it doesn't look quite as nice in my opinion. It's probably not worth breaking convention in the end (the PascalCase naming sort of hides what the icon data items are), but that can be discussed.

I brought in `quote` and `proc_macro2` since they're a bit nicer to work with than raw strings, at least for generating Rust code. They're not strictly necessary given the small scope of the codegen, so they could be removed if the maintenance desire isn't there.

I have not pushed any generated code to help make reviewing easier. If this PR is accepted, I or anyone else can commit that code before merging.

The documentation can also be improved for each public item (excluding the const icon data items, probably).

### CODE REVIEW

**Review by SorenHolstHansen — APPROVED** [review]
Great work my dude, looks amazing!

I can merge and release this when I get home

**Comment by CorvusPrudens** [comment]
Alright I added a small amount of documentation and updated the README for a new release.

I made the decision to convert the icon data items to SCREAMING_SNAKE case. As I mentioned earlier, it's a little less pleasing to my eyes, but it more clearly communicates what they actually are. Let me know if this seems okay!

One final adjustment that _could_ be made is using a `MaybeSignal` for the icon data itself. I don't care too much personally, but it could be convenient if someone wants it.

If this all looks good, I'll commit the generated code!

**Comment by SorenHolstHansen** [comment]
I think it all looks good! I have no preference regarding casing, so if you generate the code then we can merge this

**Comment by CorvusPrudens** [comment]
Alright it should be good to go from my end.

**Comment by SorenHolstHansen** [comment]
Thanks a lot for the PR! I have merged and published a new release

**Pull request merged**
