### PR TITLE
Adding icon categories as feature flags

### PR DESCRIPTION
**Pull request by ghost**
Hi there,

This adds categories as features to the cargo.toml by adding functionality in the update.rs file so that cargo xtask update:

1. Reads the existing categories from the typescript export file core/src/icons.ts. 
2. Adds the #[cfg] directives to the individual generated icon files and the mod.rs
3. Alters the projects Cargo.toml to include the above features discovered.

It adds a default feature that will by default include all the icon categories so that all current uses will work as is. 
This means however that to only use a certain set of categories, users must set default features to false in their cargo dependency.
`phosphor-leptos = { version="0.3.0", default-features = false, features = ["games"] }  `

I have included two commits with the updated files after the xtask run in the second commit.

Hope this helps, let me know your thoughts!

### CODE REVIEW

**Comment by SorenHolstHansen** [comment]
Seems great! Thanks for the PR

**Comment by SorenHolstHansen** [comment]
I have published a new version 0.3.1

**Comment by SleeplessOne1917** [comment]
This is awesome! @karoofish Is there a place where which icon is in which category is listed? I think it would be good for this to be documented if it's not already.

**Comment by ghost** [comment]
Hi @SleeplessOne1917 , until someone writes a pretty cheat sheet, I guess the easiest is to do a find inside the typescript file that the code pulls the categories from. 

It is found in a file called icons.ts in the core/src subdirectory. a grep or find on the icons name  should show you the correct icon object and the category is under a field called categories, as the icon can be under several.

Also, if you can't find the icon in the file, it evidently doesn't yet have this info on the Phosphor repo itself, and the code sets it to the feature "uncategorized".

An example of including just the Games category would be:

`phosphor-leptos = { version = "0.3.1", default-features = false, features = ["games"] }`

Hope this helps

**Comment by ghost** [comment]
@SleeplessOne1917 
Just to respond further on where the categories and icons are listed. 
I have found the best place to do this is right on the main page of [phosphoricons.com](https://phosphoricons.com/)

They list all their icons and if you search for your icon name, you will find it, and if you click on the icon, it gives you a whole bunch of tags it belongs to. 

Our categories are amongst these tags. Note, they have a much larger set of tags, but you will find which of our categories relate.

Much nicer way than looking through text files.

Hope this helps

**Pull request merged**
